version: "3.4"

services:
  video-tutorials.api:
    image: dmadouros/video-tutorials
    ports:
      - "8081:8080"
    environment:
#      - TRELLO_DATABASE_URL=jdbc:postgresql://trello.db:5432/trello?user=trello&password=trello
      - LOG4J_LAYOUT=local
    depends_on:
      - video-tutorials.eventstore.db

  video-tutorials.eventstore.db:
    image: eventstore/eventstore:21.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1114:1113"
      - "2114:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
