version: "3.4"

services:
  video-tutorials.api:
    image: dmadouros/video-tutorials
    ports:
      - "8081:8080"
    environment:
      - VIDEO_TUTORIALS_DATABASE_URL=jdbc:postgresql://video-tutorials.db:5432/video_tutorials?user=video_tutorials&password=video_tutorials
      - VIDEO_TUTORIALS_EVENTSTOREDB_URL=esdb://admin:changeit@video-tutorials.eventstore.db:2113?tls=false
      - LOG4J_LAYOUT=local
    depends_on:
      - video-tutorials.eventstore.db
      - video-tutorials.db

  video-tutorials.db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - video_tutorials_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=video_tutorials
      - POSTGRES_PASSWORD=video_tutorials
      - POSTGRES_DB=video_tutorials

  video-tutorials.eventstore.db:
    image: eventstore/eventstore:21.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113"
      - "2114:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  video_tutorials_db_data:
